directory = "datasets"

[[datasets]]
name = "dvs09"
url = "https://www.undr.space/dvs09/"
mode = "disabled"

[[datasets]]
name = "dvsact16"
url = "https://www.undr.space/dvsact16/"
mode = "disabled"

[[datasets]]
name = "dvsflow16"
url = "https://www.undr.space/dvsflow16/"
mode = "disabled"

[[datasets]]
name = "ncaltech101"
url = "https://www.undr.space/ncaltech101/"
mode = "disabled"

[[datasets]]
name = "nmnist"
url = "https://www.undr.space/nmnist/"
mode = "disabled"
