name: Test Python

on:
  push:
    branches:
      - main

jobs:
  build_sdist:
    if: ${{ !startsWith(github.event.head_commit.message, '[doc]') }}
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - run: python setup.py sdist
          working-directory: python
        - uses: actions/upload-artifact@v3
          with:
            name: undr-sdist
            path: python/dist/*.tar.gz
  import_library:
    needs: [build_sdist]
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Import library on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/download-artifact@v3
        with:
          name: undr-sdist
          path: dist
      - run: ls -R
      - run: python -m pip install dist/*.tar.gz
      - run: python -c 'import undr'
