name: Test App

on:
  push:
    branches:
      - main
env:
    CIBW_ARCHS_MACOS: x86_64 arm64
    CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x

jobs:
  build:
    name: Build the library
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y \
              libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev
        - run: npm install
          working-directory: app
        - run: npm run tauri build -- --debug
          working-directory: app
